export {default as Error} from './Error';
export {default as Footer} from './Footer';
export {default as Gallery} from './Gallery';
export {default as Logo} from './Logo';
export {default as Nav} from './Nav';
export {default as NavLink} from './NavLink';
export {default as PortfolioCard} from './PortfolioCard';
export {default as SocialLinks} from './SocialLinks';
export {default as Tagline} from './Tagline';
